//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemHotelowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dania
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dania()
        {
            this.RachunkiZaDania = new HashSet<RachunkiZaDania>();
        }
    
        public int IdDania { get; set; }
        public string Typ { get; set; }
        public string Nazwa { get; set; }
        public double Cena { get; set; }
        public string Opis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RachunkiZaDania> RachunkiZaDania { get; set; }
    }
}
