//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemHotelowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meldunki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meldunki()
        {
            this.RachunkiZaPobyt = new HashSet<RachunkiZaPobyt>();
        }
    
        public int IdMeldunku { get; set; }
        public int IdRezerwacji { get; set; }
        public System.DateTime DataOd { get; set; }
        public System.DateTime DataDo { get; set; }
        public bool CzyAktywny { get; set; }
        public int IdPracownika { get; set; }
        public int LiczbaOsob { get; set; }
        public int LiczbaDob { get; set; }
    
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Rezerwacje Rezerwacje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RachunkiZaPobyt> RachunkiZaPobyt { get; set; }
    }
}
