//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemHotelowy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class INZ2020HotelePKEntities : DbContext
    {
        public INZ2020HotelePKEntities()
            : base("name=INZ2020HotelePKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dania> Dania { get; set; }
        public virtual DbSet<Klienci> Klienci { get; set; }
        public virtual DbSet<Meldunki> Meldunki { get; set; }
        public virtual DbSet<Pokoje> Pokoje { get; set; }
        public virtual DbSet<Pracownicy> Pracownicy { get; set; }
        public virtual DbSet<RachunkiZaDania> RachunkiZaDania { get; set; }
        public virtual DbSet<RachunkiZaPobyt> RachunkiZaPobyt { get; set; }
        public virtual DbSet<RachunkiZaUslugi> RachunkiZaUslugi { get; set; }
        public virtual DbSet<Rezerwacje> Rezerwacje { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Uslugi> Uslugi { get; set; }
        public virtual DbSet<Uzytkownicy> Uzytkownicy { get; set; }
    }
}
