//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemHotelowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class RachunkiZaPobyt
    {
        public int IdRachunkuZaPobyt { get; set; }
        public int IdMeldunku { get; set; }
        public double Kwota { get; set; }
        public System.DateTime TerminZaplaty { get; set; }
        public bool CzyZaplacono { get; set; }
        public int IdPracownika { get; set; }
    
        public virtual Meldunki Meldunki { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
    }
}
