//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemHotelowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezerwacje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezerwacje()
        {
            this.Meldunki = new HashSet<Meldunki>();
        }
    
        public int IdRezerwacji { get; set; }
        public int IdKlienta { get; set; }
        public int IdPokoju { get; set; }
        public System.DateTime DataOd { get; set; }
        public System.DateTime DataDo { get; set; }
        public bool CzyAktywna { get; set; }
        public int IdPracownika { get; set; }
        public int LiczbaOsob { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meldunki> Meldunki { get; set; }
        public virtual Pokoje Pokoje { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
    }
}
