//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemHotelowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzytkownicy
    {
        public int IdUzytkownika { get; set; }
        public int IdPracownika { get; set; }
        public string Login { get; set; }
        public string Haslo { get; set; }
    
        public virtual Pracownicy Pracownicy { get; set; }
    }
}
